theme: jekyll-theme-dinky

title: <a href='/mif13/2018'>M1IF13 Web Avancé</a>
description: [<ul><li><a href='/mif13/2018/#plan-du-cours'>Cours</a></li><li><a href='/mif13/2018/#tp'>TP</a></li><li><a href='/mif13/2018/exposes'>Exposés</a></li></ul>]
